default_config:

tts:
  - platform: google_translate
    language: ru

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

group: !include groups.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary-sensors
template: !include_dir_merge_list template

homeassistant:
  packages: !include_dir_named conf
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

morph_numbers:
start_time:

discovery:
  ignore:
    - homekit
    - yeelight
    - openhome

yeelight: !include yeelight.yaml

homekit:
  - filter:
      include_entities:
        - switch.0x04cf8cdf3c76548d_plug
    entity_config:
      switch.0x04cf8cdf3c76548d_plug:
        type: outlet

logger:
  default: info
#  logs:
    #pysqueezebox.server: fatal
    #homeassistant.components.zha: debug
    #zigpy: debug

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - device_class
  include:
    entities: !include influxdb-whitelist.yaml
    entity_globs:
      - sensor.*_humidity
      - sensor.*_temperature
      - sensor.*_illuminance_lux
      - sensor.*radiacode*
      - sensor.*_pressure

input_boolean:
  manual_light_off:
    name: "Лампа выключена вручную"
    initial: off
  manual_effects_on:
    name: "Эффекты гирлянды"
    initial: on

shell_command:
  radiacode_kill: 'ssh -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa ans@192.168.1.252 tmux kill-session -t radiacode || exit 0'
  radiacode_start: 'ssh -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa ans@192.168.1.252 tmux new -d -s radiacode "python3 /home/ans/homeassistant.py --bluetooth-mac 52:43:06:50:01:54 --interval 1"'

folder_watcher:
  - folder: /media
    patterns:
      - '*.mp4'

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

#zha:
#  zigpy_config:
#    ota:
#      otau_directory: /config/zigpy_ota
#      ikea_provider: true
#      ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json
#      ledvance_provider: true
