default_config:

tts:
  - platform: google_translate
    language: ru

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/24
    - 172.30.32.0/23

group: !include groups.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary-sensors
template: !include_dir_merge_list template

homeassistant:
  packages: !include_dir_named conf
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config
    - /share/smartctl

morph_numbers:
start_time:
powercalc:
python_script:
battery_notes:

yeelight: !include yeelight.yaml

logger:
  default: info
  #logs:
    #homeassistant.components.zha: debug
    #zigpy: debug

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - device_class
  include:
    entities: !include influxdb-whitelist.yaml
    entity_globs:
      - sensor.*_humidity
      - sensor.*_temperature
      - sensor.*_illuminance_lux
      - sensor.*radiacode*
      - sensor.*_pressure

input_boolean:
  manual_light_off:
    name: "Лампа выключена вручную"
    initial: off
  manual_effects_on:
    name: "Эффекты гирлянды"
    initial: on

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

config_editor:
