default_config:

tts:
  - platform: google_translate
    language: ru

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

group: !include groups.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary-sensors
template: !include_dir_merge_list template

homeassistant:
  packages: !include_dir_named conf
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  allowlist_external_dirs:
    - /config

recorder:
  commit_interval: 120
  exclude:
    domains:
      - automation
      - scene
  include:
    entities:
      - automation.zvonok_v_domofon

morph_numbers:
start_time:
powercalc:

discovery:
  ignore:
    - homekit
    - yeelight
    - openhome

yeelight: !include yeelight.yaml

#homekit:
#  - filter:
#      include_entities:
#        - switch.0x04cf8cdf3c76548d_plug
#    entity_config:
#      switch.0x04cf8cdf3c76548d_plug:
#        type: outlet

logger:
  default: info
  #logs:
    #custom_components.openweathermap: debug
    #pysqueezebox.server: fatal
    #homeassistant.components.zha: debug
    #zigpy: debug

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - device_class
  include:
    entities: !include influxdb-whitelist.yaml
    entity_globs:
      - sensor.*_humidity
      - sensor.*_temperature
      - sensor.*_illuminance_lux
      - sensor.*radiacode*
      - sensor.*_pressure

input_boolean:
  manual_light_off:
    name: "Лампа выключена вручную"
    initial: off
  manual_effects_on:
    name: "Эффекты гирлянды"
    initial: on

#input_text:
#  ans_phone_number:
#    name: ANS phone number
#    initial: !secret sms_ans

folder_watcher:
  - folder: /media
    patterns:
      - '*.mp4'
      - '*.jpg'

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

#weather:
#  - platform: yandex_weather
#    api_key: !secret yandex_weather_key

#zha:
#  zigpy_config:
#    ota:
#      otau_directory: /config/zigpy_ota
#      ikea_provider: true
#      ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json
#      ledvance_provider: true
