######################################
# Оповещение о низком заряде батарей #
######################################

input_number:

  scale_minimal_battery:
    name: "Уровень заряда"
    min: 5
    max: 20
    step: 5
    mode: slider
    unit_of_measurement: "%"
    icon: mdi:battery-alert

automation:

  - id: alarm_battery
    alias: "Alarm battery"
    initial_state: true
    trigger:
      - platform: time
        at: "20:30:00"
      - platform: homeassistant
        event: start

    condition:
      - condition: template
        value_template: >
          {% macro battery_level(unknown=false) %}
          {%- set threshold = states('input_number.scale_minimal_battery') | int(10) -%}
          {%- for domain in states | groupby('domain') | map(attribute='0') | list -%}
            {%- for item in states[domain] if ( (("battery" in item.name | lower or "battery" in item.entity_id | lower) and ((item.state | int(0) < threshold and item.state | int(0) != 0) or (item.state | lower == "low")))) -%}
            {%- set device = (area_name(item.entity_id) | string + " - " if area_name(item.entity_id) != item.name) + (device_attr(device_id(item.entity_id), 'name') if device_attr(device_id(item.entity_id), 'name') | string != '') -%}
            {{ item.name }}{% if not loop.last %}, {%- endif %} 
          {%- endfor %}
          {%- endfor %}
          {%- endmacro -%}
          {{ battery_level() | trim != "" }}

    action:
      - service: telegram_bot.send_message
        data:
          target:
            - !secret telegram_bot_allowed_chat_id1
          message: |
            {{'\u267B\uFE0F'}} Похоже, садится батарейка:
            {% macro battery_level(unknown=false) -%}
              {% set ns = namespace(devices=[]) %}
              {%- set threshold = states('input_number.scale_minimal_battery') | int(10) -%}
              {%- for domain in states | groupby('domain') | map(attribute='0') | list -%}
                {%- for item in states[domain] if ( (("battery" in item.name | lower or "battery" in item.entity_id | lower) and ((item.state | int(0) < threshold and item.state | int(0) != 0) or (item.state | lower == "low")))) -%}
                  {%- set device = (area_name(item.entity_id) | string + " - " if area_name(item.entity_id) != item.name) + (device_attr(device_id(item.entity_id), 'name') if device_attr(device_id(item.entity_id), 'name') | string != '') -%}
                  {%- macro battery_lifetime(unknown=false) -%}
                    {% set uptime = ((now() | as_timestamp - item.attributes['battery_change'] | as_timestamp)) | int -%}
                    {% set days = ((uptime / 86400) % 30) | int -%}
                    {% set months = (uptime / 2592000) | int -%}
                    {%- if months > 0 -%} 
                        {{ months |format(morph='месяц', as_text=false) }}
                    {%- endif -%} 
                    {%- if days > 0 -%} 
                      {%- if months > 0 -%} 
                        {{ ', ' }} 
                      {%- endif -%}   
                    {%- endif -%} 
                    {%- if days > 0 -%} 
                        {{ days |format(morph='день', as_text=false) }}
                    {%- endif -%} 
                  {%- endmacro -%}
                  {%- set value = item.name|replace(" battery","")|replace(" Battery","")+ ' -' + ((' *' + item.attributes['battery_type'] + '*') if item.attributes.battery_type is defined else '') + ' ' + (item.attributes['battery_level'] | string + '%' if item.attributes.battery_level is defined else item.state_with_unit | string | replace(' ','')) + ((' (' + battery_lifetime(true) +')') if item.attributes['battery_change'] is defined and item.attributes['battery_change'] | as_timestamp != None else '') -%}
                  {% set json = {"device": device, "value": value } -%}
                  {% set ns.devices = ns.devices + [ json ] %}
                {%- endfor %}
              {%- endfor -%}
              {%- for d, i in ns.devices | groupby('device') %}
            *{{ d }}*
                {%- for v in (i | map(attribute='value') | join ('|')).split('|') | select('ne', '') | sort | unique | list %}
            - {{ v }}
                {%- endfor -%}
              {%- endfor -%}
            {%- endmacro -%}
            {{ battery_level(true) }}