# ##################################
#   Автоматизация света на кухне   #
# ##################################

template:
  - binary_sensor:
      - name: "AutoOffKitchen"
        delay_off:
          minutes: 3
        state: >
          {{ states('binary_sensor.prisutstvie_na_kukhne') }}

automation:
  - alias: Turn ON kitchen lights (motion on)
    id: turn_kitchen_on
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.dd_na_kukhne_occupancy
          - binary_sensor.ble_dd_motion
          - binary_sensor.autooffkitchen
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states('light.kukhnia_hue') != 'on' and
          states('light.kukhnia_potolok') != 'on' and
          states('light.kitchen') != 'on' }}
      - condition: numeric_state
        entity_id: sensor.osveshchionnost_na_kukhne_illuminance_lux
        below: "2"
    action:
      - parallel:
          - service: light.turn_on
            data:
              brightness: 1
            target:
              entity_id: light.kukhnia_potolok

  - alias: Turn OFF (LT) Timer Off
    id: turn_kitchen_off_timer_off
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.autooffkitchen
        to: "off"
    condition:
      - condition: template
        value_template: >-
          {{ states('light.kukhnia_potolok') == 'on' and
          states('light.kitchen') != 'on' and
          state_attr('light.kukhnia_potolok', 'brightness') | float(0) == 1 }}
    action:
      - service: light.turn_off
        data:
          entity_id: light.kukhnia_potolok

    mode: single
