######################################
# Сенсоры радиации c RadiaCode-101 и #
# пересчёт значений с Zigbee гейгера #
######################################

template:

  - trigger:
      - platform: state
        entity_id:
          - sensor.geiger_counter_radiation_dose_per_hour
        not_to:
          - "unavailable"
          - "unknown"
    sensor:
      - name: "Geiger counter dose rate"
        unique_id: geiger-dr
        state: "{% set drmr = trigger.to_state.state | float(0) / 114.025 %} {{ drmr | round(2) }}"
        unit_of_measurement: "μSv/h"
        icon: mdi:radioactive

  - trigger:
      - platform: state
        entity_id:
          - sensor.radiacode
        not_to:
          - "unavailable"
          - "unknown"
    sensor:
      - name: "Radiacode dose rate"
        unique_id: radiacode-dr
        state: "{{ trigger.to_state.state }}"
        unit_of_measurement: "μSv/h"
        icon: mdi:radioactive
      - name: "Radiacode count rate"
        unique_id: radiacode-cr
        state: "{{ trigger.to_state.attributes.cps }}"
        unit_of_measurement: "CPS"
        icon: mdi:radioactive

  - trigger:
      - platform: state
        entity_id:
          - sensor.radiacode_work
        not_to:
          - "unavailable"
          - "unknown"
    sensor:
      - name: "Radiacode (work) dose rate"
        unique_id: radiacode-work-dr
        state: "{{ trigger.to_state.state }}"
        unit_of_measurement: "μSv/h"
        icon: mdi:radioactive
      - name: "Radiacode (work) count rate"
        unique_id: radiacode-work-cr
        state: "{{ trigger.to_state.attributes.cps }}"
        unit_of_measurement: "CPS"
        icon: mdi:radioactive

sensor:

  - platform: statistics
    name: radiacode_dr_mean_value
    entity_id: sensor.radiacode_dose_rate
    sampling_size: 1500
    state_characteristic: mean
    max_age:
      hours: 24

  - platform: statistics
    name: radiacode_cr_mean_value
    entity_id: sensor.radiacode_count_rate
    sampling_size: 1500
    state_characteristic: mean
    max_age:
      hours: 24

  - platform: statistics
    name: geiger_dr_mean_value
    entity_id: sensor.geiger_dose_rate
    sampling_size: 1500
    state_characteristic: mean
    max_age:
      hours: 24

  - platform: statistics
    name: geiger_cr_mean_value
    entity_id: sensor.geiger_counter_radioactive_events_per_minute
    sampling_size: 1500
    state_characteristic: mean
    max_age:
      hours: 24
