#######################################
#    Сенсоры доступности Интернета    #
#######################################

- platform: template
  sensors:
    internet:
      value_template: "{{ bool(states('binary_sensor.google'), false) or bool(states('binary_sensor.yandex'), false) }}"
      device_class: connectivity
