#######################################
#      Сенсоры адаптивного света      #
#######################################

- platform: template
  sensors:
    adaptive_brt:
      friendly_name: "Адаптивная яркость"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.adaptive_lighting_room', 'brightness_pct') }}"
    adaptive_ct:
      friendly_name: "Адаптивная температура"
      unit_of_measurement: 'K'
      value_template: "{{ state_attr('switch.adaptive_lighting_room', 'color_temp_kelvin') }}"
