# Автоматизация света на кухне
- alias: Turn ON kitchen lights (motion on)
  id: turn_kitchen_on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.dd_na_kukhne_occupancy
        - binary_sensor.ble_dd_motion
      to: "on"
  #    - platform: state
  #      entity_id: binary_sensor.ble_dd_motion
  #      to: 'on'
  condition:
    - condition: state
      entity_id: timer.dvizhenie_na_kukhne
      state: "idle"
    - condition: template
      value_template: >-
        {{ states.light.kukhnia_hue.state == 'off' and
        states.light.kukhnia_potolok.state == 'off' and
        states.light.dimmable_light_2.state == 'off' }}
    - condition: numeric_state
      entity_id: sensor.osveshchionnost_na_kukhne_illuminance_lux
      below: "3"
  action:
    - parallel:
        - service: light.turn_on
          data:
            brightness: 1
          target:
            entity_id: light.kukhnia_potolok
        - service: timer.start
          entity_id: timer.dvizhenie_na_kukhne
#      - service: notify.telegram
#        data:
#          message: "Свет на кухне. Время включения: {{ states('sensor.time') }}"

- alias: Turn OFF (LT) Timer On
  id: turn_kitchen_off_timer_on
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dvizhenie_na_kukhne
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.dd_na_kukhne_occupancy
        state: "on"
      - condition: state
        entity_id: binary_sensor.ble_dd_motion
        state: "on"
  action:
    - parallel:
        - service: timer.start
          entity_id: timer.dvizhenie_na_kukhne
#      - service: notify.telegram
#        data:
#          message: "Свет на кухне. Время продления: {{ states('sensor.time') }}"

- alias: Turn OFF (LT) Timer Off
  id: turn_kitchen_off_timer_off
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dvizhenie_na_kukhne
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dd_na_kukhne_occupancy
        state: "off"
      - condition: state
        entity_id: binary_sensor.ble_dd_motion
        state: "off"
      - condition: or
        conditions:
          - condition: template
            value_template: >-
              {{ states.light.kukhnia_potolok.context.id ==
              states.automation.turn_on_light_kitchen_motion_on.context.id and
              states.light.kukhnia_potolok.state == 'on' and
              states.light.dimmable_light_2.state == 'off' and
              state_attr('light.kukhnia_potolok', 'brightness') | float(0) == 1 }}
          - condition: template
            value_template: >-
              {{ states.light.kukhnia_potolok.context.id ==
              states.automation.turn_off_lt_timer_on.context.id and
              states.light.kukhnia_potolok.state == 'on' and
              states.light.dimmable_light_2.state == 'off' and
              state_attr('light.kukhnia_potolok', 'brightness') | float(0) == 1 }}
  action:
    - service: light.turn_off
      data:
        entity_id: light.kukhnia_potolok

- alias: Turn OFF (Hue) Timer Cancel
  id: turn_kitchen_off_timer_cancel
  trigger:
    - device_id: ea28b7c45cdbd3c8d68374d447b6b3ac
      domain: hue
      platform: device
      type: initial_press
      subtype: 4
      unique_id: eab0a07c-82b1-4542-8b4d-0301a5422ed6
  action:
    - service: timer.cancel
      target:
        entity_id: timer.dvizhenie_na_kukhne
  mode: single
