#######################################
#          Меню в Telegram            #
#######################################

- alias: Telegram Menu start
  id: telegram_menu_start
  description: "Обработка первого запуска бота и показ основного меню"

  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: /start
    - platform: event
      event_type: telegram_callback
      event_data:
        command: /back

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/start" }}'
          sequence:
            - service: telegram_bot.send_message
              data:
                message: &stmsg |
                  {{ [ "Что желаете, Повелитель?", "Что я могу для Вас сделать?", "Внимаю!", "Хорошего дня" ] | random }}

                  {% if is_state("sun.sun", "above_horizon") -%} Солнце уже встало. 
                  {%- else -%} Солнце встанет в {{ as_timestamp(state_attr("sun.sun", "next_rising")) | timestamp_custom('%H:%M') }}. {%- endif %}
                  Сейчас за бортом {{ state_attr('weather.yandex_weather','yandex_condition') | lower }}.
                  Температура {{state_attr('weather.yandex_weather','temperature') | int(0) }}°C, ощущается {% if state_attr('weather.yandex_weather','temperature') | int(0) == state_attr('weather.yandex_weather','feels_like') | int(0) %}так же. {% else %}как {{state_attr('weather.yandex_weather','feels_like') | int(0) }}°C.{% endif %} Влажность {{state_attr('weather.yandex_weather','humidity')}} %.
                  Скорость ветра {{ state_attr('weather.yandex_weather','wind_speed') | int(0) }} м/с.
                  {%if states.light | selectattr('entity_id') |
                  selectattr('state','eq','on') | map(attribute='entity_id') | list | count == 0 %}Свет везде выключен.
                  {% else %}Свет включен.{% endif %}
                  Завтра
                  {%- if now().weekday() in (0,) %} вторник 
                  {%- elif now().weekday() in (1,) %} среда 
                  {%- elif now().weekday() in (2,) %} четверг 
                  {%- elif now().weekday() in (3,) %} пятница 
                  {%- elif now().weekday() in (4,) %} суббота 
                  {%- elif now().weekday() in (5,) %} воскресенье 
                  {%- elif now().weekday() in (6,) %} понедельник 
                  {%- endif -%},
                  {%- if is_state('binary_sensor.workday_tomorrow','on') and is_state('input_boolean.wakeup_disabled','off') %} рабочий день, {{ states('input_select.wakeup_time') | lower }}, 
                  {%- else %} выходной день,
                  {%- endif %} будильник
                  {%- if is_state('input_boolean.wakeup_enabled','on') %} 
                    {%- if is_state('binary_sensor.workday_tomorrow','on') and is_state('input_boolean.wakeup_disabled','off') %} сработает в
                      {%- if is_state('input_select.wakeup_time','Метро') %} {{ state_attr('input_datetime.wakeup_office_time', 'timestamp') | timestamp_custom('%H:%M', false) }}.
                      {%- elif is_state('input_select.wakeup_time','Машина') %} {{ state_attr('input_datetime.wakeup_office_car_time', 'timestamp') | timestamp_custom('%H:%M', false) }}.
                      {%- elif is_state('input_select.wakeup_time','Сидим дома') %} {{ state_attr('input_datetime.wakeup_homeoffice_time', 'timestamp') | timestamp_custom('%H:%M', false) }}.
                      {%- endif -%}
                    {%- elif is_state('input_boolean.wakeup_weekend','on') and is_state('input_boolean.wakeup_disabled','on') %} сработает в {{ state_attr('input_datetime.wakeup_weekend_time', 'timestamp') | timestamp_custom('%H:%M', false) }}
                    {%- else %} выключен.
                    {%- endif -%}
                  {%- else %} выключен.
                  {%- endif %}
                parse_mode: markdown
                disable_notification: true
                disable_web_page_preview: true
                timeout: 500
                inline_keyboard: &mainkeyb
                  - 💡 Свет:/lights, ⏰ Будильник:/wakeup
                  - ℹ Датчики:/status, 💻 Система:/system
                  - 🦾 Запустить уборку:/vacuum_start
                  - ☢️ Радиация:/radiation, 📸 Фото с домофона:/photo_entrance
                target: "{{ trigger.event.data.chat_id }}"
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/back" }}'
          sequence:
            - service: telegram_bot.edit_message
              data:
                message_id: last
                chat_id: "{{ trigger.event.data.chat_id }}"
                message: *stmsg
                inline_keyboard: *mainkeyb
                target: "{{ trigger.event.data.chat_id }}"
  mode: single
