###################################
#    Меню в Telegram: Датчики     #
###################################

- alias: Telegram Menu Sensors
  id: telegram_menu_sensors
  description: "Статус датчиков и света"

  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: /status

  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: Запрос статуса датчиков
    - service: script.dynamic_update_all_light_group
      data: {}
    - service: telegram_bot.edit_message
      data_template:
        message_id: last
        chat_id: "{{ trigger.event.data.chat_id }}"
        message: |-
          *Температура в комнате* {{states('sensor.582d3439b574_temperature')|round(0)|format(morph='градус',as_text=false)}}.
          *Температура на кухне* {{states('sensor.ble_temperature_datchik_na_kukhne')|round(0)|format(morph='градус',as_text=false)}}.
          *Влажность в комнате* {{states('sensor.582d3439b574_humidity')|round(0)}}%
          *Влажность на кухне* {{states('sensor.ble_humidity_datchik_na_kukhne')|round(0)}}%
          {% if is_state("binary_sensor.okno_v_komnate_contact", "off")%}
          Окно в спальне закрыто. {% else %} *Окно в спальне открыто!* {% endif %}
          {% if is_state("binary_sensor.okno_na_kukhne_contact", "off")%}
          Окно на кухне закрыто. {% else %}*Окно на кухне открыто!* {% endif %}
          {%if states.light | selectattr('entity_id') |
          selectattr('state','eq','on') | map(attribute='entity_id') | list | count == 0 %}
          *Свет* везде выключен.
          {% else %}
          *Свет* включен: {{ states.light | selectattr("state", "eq", "on") 
          | map(attribute  = "name") | join(", ") }}.
          {% endif %}
        inline_keyboard:
          - Назад:/back

  mode: single