###################################
#     Меню в Telegram: Свет       #
###################################

- alias: Telegram Menu Lights
  id: telefram_menu_lights
  description: "Управление светом через Telegram"

  trigger:
    - platform: event
      event_type: telegram_callback
      event_data: {}

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/lights" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: Что Вы хотите сделать со светом?
            - service: telegram_bot.edit_message
              data:
                message_id: last
                chat_id: "{{ trigger.event.data.chat_id }}"
                message: &msg |
                  {%if states.light | selectattr('entity_id') |
                  selectattr('state','eq','on') | map(attribute='entity_id') | list | count == 0 %}*Свет* везде выключен.
                  {% else %}*Свет* включен: {{ states.light | selectattr("state", "eq", "on") |
                  map(attribute  = "name") | join(", ") }}.{% endif %}
                inline_keyboard: &keyb
                  - Включить свет в комнате:/lighton
                  - '{% if is_state("light.prikhozhaia", "off")%}{{"🔴"}}{%else %}{{"🟢"}}{% endif %} Прихожая:/lobby_toggle,
                    {% if is_state("light.kukhnia_hue", "off") %}{{"🔴"}}{% else %}{{"🟢"}}{%endif %} Кухня:/kitchen_toggle'
                  - '{% if is_state("light.torsher_2", "off") %}{{"🔴"}}{%else %}{{"🟢"}}{% endif %} Торшер:/torsher_toggle,
                    {% if is_state("light.torsherchik", "off") %}{{"🔴"}}{%else %}{{"🟢"}}{% endif %} Настольная:/torsherchik_toggle'
                  - '{% if is_state("light.living_room", "off") %}{{"🔴"}}{%else %}{{"🟢"}}{% endif %} Лампа:/living_toggle,
                    {% if is_state("light.liustra", "off") %}{{"🔴"}}{% else %}{{"🟢"}}{%endif %} Люстра:/liustra_toggle'
                  - Выключить ВСË:/lightoff
                  - Назад:/back
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/lighton" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: "Включаю обычный свет :)"
            - service: script.1599944056170
              data: {}
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/lobby_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: Переключаю свет в прихожей.
            - service: light.toggle
              target:
                entity_id: light.prikhozhaia
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/kitchen_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: '{% if is_state("light.kukhnia_hue", "off")%}{{"Включаю свет на кухне."}}{%else %}{{"Выключаю свет на кухне."}}{% endif %}'
            - service: light.toggle
              target:
                entity_id: light.kukhnia_hue
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/torsher_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: '{% if is_state("light.torsher_2", "off")%}{{"Включаю торшер в спальне."}}{%else %}{{"Выключаю торшер в спальне."}}{% endif %}'
            - service: light.toggle
              target:
                entity_id: light.torsher
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/torsherchik_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: '{% if is_state("light.torsherchik", "off")%}{{"Включаю настольную лампу."}}{%else %}{{"Выключаю настольную лампу."}}{% endif %}'
            - service: light.toggle
              target:
                entity_id: light.torsherchik
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/living_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: '{% if is_state("light.living_room", "off")%}{{"Включаю лампу в спальне."}}{%else %}{{"Выключаю лампу в спальне."}}{% endif %}'
            - service: light.toggle
              target:
                entity_id: light.living_room
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/liustra_toggle" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: '{% if is_state("light.liustra", "off")%}{{"Включаю люстру в спальне."}}{%else %}{{"Выключаю люстру в спальне."}}{% endif %}'
            - service: light.toggle
              target:
                entity_id: light.liustra
            - delay:
                milliseconds: 500
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/lightoff" }}'
          sequence:
            - service: telegram_bot.answer_callback_query
              data_template:
                callback_query_id: "{{ trigger.event.data.id }}"
                message: Выключаю весь свет!
            - service: script.1644819849093
              data: {}
            - delay:
                milliseconds: 2000
            - service: telegram_bot.edit_message
              data:
                message_id: "{{ trigger.event.data.message.message_id }}"
                chat_id: "{{ trigger.event.data.chat_id }}"
                callback_query_id: "{{ trigger.event.data.id }}"
                message: *msg
                inline_keyboard: *keyb
      default: []

  mode: queued
