###################################
#        Меню в Telegram          #
###################################

- alias: Telegram Menu start
  id: telegram_menu_start
  description: "Обработка первого запуска бота и показ основного меню"

  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: /start
    - platform: event
      event_type: telegram_callback
      event_data:
        command: /back

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/start" }}'
          sequence:
            - service: telegram_bot.send_message
              data:
                message: &stmsg >
                  {{ [ "Что желаете, Повелитель?", "Что я могу для Вас сделать?", "Внимаю!", "Хорошего дня" ] | random }}
                parse_mode: html
                disable_notification: true
                disable_web_page_preview: true
                timeout: 500
                inline_keyboard: &mainkeyb
                  - 💡 Свет:/lights, ℹ Статус:/status
                  - ☀ Погода:/weather, 💻 Система:/system
                  - 🦾 Запустить уборку:/vacuum_start
                  - ☢️ Радиация:/radiation, 📸 Фото с домофона:/photo_entrance
                target: "{{ trigger.event.data.chat_id }}"
        - conditions:
            - condition: template
              value_template: '{{ trigger.event.data.command == "/back" }}'
          sequence:
            - service: telegram_bot.edit_message
              data:
                message_id: last
                chat_id: "{{ trigger.event.data.chat_id }}"
                message: *stmsg
                inline_keyboard: *mainkeyb
                target: "{{ trigger.event.data.chat_id }}"

  mode: single
